export const LOCK_CONFIG = {
  MOVEMENT_THRESHOLD: 0.12,
  INACTIVITY_TIMEOUT_MS: 5 * 60 * 1000,
  BLUR_TIMEOUT_MS: 2 * 60 * 1000,
  UPDATE_INTERVAL_MS: 500,
};

export const STORAGE_KEYS = {
  PIN: "pin",
};
